version: '3.1'

services:
  web-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-nextjs
    ports:
      - "3000:3000"
    env_file: 
      - ./docker-env/development.env
